databases:
  - name: my-database
    databaseName: my_app_db
    user: my_app_user
services:
  - type: web
    runtime: node
    name: my-node-app
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: NODE_ENV
        value: production
    preDeployCommand: npx prisma migrate deploy; npx prisma db seed
